### ISSUE TITLE
astroI18n.langCode switched after build

### ISSUE THREAD

**Issue by narduin** [Alexandre-Fernandez/astro-i18n#6] opened 2022-12-06 18:21 UTC
Hi, this is a weird one.

While on dev mode, `astroI18n.langCode` works as expected. But after running `astro build`, it is actually reversed. I tested with two and three locales available. The `en` locale seems to become the default, messing up translations (but not routing).

[See reproduction here.](https://codesandbox.io/p/sandbox/gifted-christian-swmcb9)

**Comment by Alexandre-Fernandez** [comment] 2022-12-06 18:27
I tested the build on a local project and it works fine, can you please provide a git repo that I can clone for the reproduction ?

**Comment by Alexandre-Fernandez** [comment] 2022-12-06 19:44
This is happening because you reassign `astroI18n.langCode` in the frontmatter.
```astro
---
const currentLocale = astroI18n.langCode; // you should use `astroI18n.langCode` directly instead of reassigning it
---
```
Because ` astroI18n.langCode` is a string, when it changes your variable `currentLocale` stays on the outdated langCode.

**Closed by Alexandre-Fernandez** 2022-12-06 19:44 UTC

**Comment by narduin** [comment] 2022-12-06 19:57
ok thanks a lot did not know that

**Comment by Alexandre-Fernandez** [comment] 2022-12-07 11:02
I should update the documentation, `astroI18n.langCode` will only be up to date inside the `I18nProvider`.
Inside means, not in the frontmatter of the component that use `I18nProvider` (directly like in your `Layout` component or indirectly by using your `Layout` component).

**Comment by narduin** [comment] 2022-12-08 12:28
I've had some really weird behaviour from `astroI18n.langCode` used in frontmatter of a component inside a `Layout` containing `I18nProvider`.
For example, using a `filter()` against it would not work as expected when building.

I've managed to find a workaround by using it in the code directly. I've updated [the demo repo](https://github.com/narduin/astro-i18n-test) with the two behaviours if you want to check it out.

I need to find a way to update the `lang` attribute which is currently outside the `I18nProvider` in the layout.

**Comment by Alexandre-Fernandez** [comment] 2022-12-21 16:15
> I've had some really weird behaviour from `astroI18n.langCode` used in frontmatter of a component inside a `Layout` containing `I18nProvider`. For example, using a `filter()` against it would not work as expected when building.
> 
> I've managed to find a workaround by using it in the code directly. I've updated [the demo repo](https://github.com/narduin/astro-i18n-test) with the two behaviours if you want to check it out.
> 
> I need to find a way to update the `lang` attribute which is currently outside the `I18nProvider` in the layout.

@narduin As explained in my previous comment, `astroI18n.langCode` cannot be used in the same level as `<I18nProvider>` no matter if `<I18nProvider>` is inside a layout or not. 
In other words if you have `<I18nProvider>` or a `<Layout>` containing a provider in the current page, `astroI18n.langCode` will not behave as expected in the page's frontmatter.
This is a limitation of astro due to the order of frontmatter executions. Unfortunately there's no way that I know of to run an initialization code for the current page, the closest thing is a wrapper component (`<I18nProvider>`).
