### ISSUE TITLE
astro@2.4.4 broke collection content translation

### ISSUE THREAD

**Issue by narduin** [Alexandre-Fernandez/astro-i18n#34] opened 2023-05-17 15:59 UTC
Hi!

Updating to [astro@2.4.4](https://github.com/withastro/astro/releases/tag/astro%402.4.4) broke my collection translation logic, I could not find a workaround yet.
I suspect it has to do with [this PR](https://github.com/withastro/astro/pull/6916) but I can't be certain…

Right now I have a content collection called 'articles' with two subfolders (`en` and `fr`).
Inside `src/pages/articles/[slug].astro`, I'm using the following logic to get the translated articles:

```js
import { astroI18n } from "astro-i18n";
astroI18n.init(Astro); // does not change anything if present or not

export async function getStaticPaths() {
	const articles = await getCollection("articles", ({ data }) => {
		// I have a frontmatter property called lang in each article.
		// I tried using the id filter as seen in the astro docs but no luck either.
		return data.lang === astroI18n.langCode;
	});
	return articles.map((article) => ({
		params: { slug: article.slug },
		props: { article },
	}));
}
```

What happens is the frontmatter translates correctly but the acutal content does not. When building the website, the same version of the content will be displayed on both languages instead of its translation.

Reverting back to astro@2.4.3 resolves everything 😅 
I tested with `astro-i18n v1.7.0` and `v1.6.1` and `astro@2.4.5` as well.
I have [a branch](https://git.nardu.in/nardu.in/website-astro/src/branch/bug/2.4.4) available for reproduction.

**Comment by Alexandre-Fernandez** [comment] 2023-05-18 10:24
I found a fix for this that should not only fix the issue but simplify your logic. I'm implementing it right now, thanks for the reproduction repository saves lots of time.

**Comment by Alexandre-Fernandez** [comment] 2023-05-18 11:25
You should be able to use `extractRouteLangCode(import.meta.url)` to retrieve the lang code in v1.7.1 (https://github.com/Alexandre-Fernandez/astro-i18n#extractroutelangcode).
I think this happens because `getStaticPaths` runs before `astroI18n.init(Astro)`.

**Comment by narduin** [comment] 2023-05-18 17:47
Thanks a lot for the quick fix!
I was not able to implement it however… Could you provide an example using `extractRouteLangCode(import.meta.url)`?

I tried the following:

```js
export async function getStaticPaths() {
	const articles = await getCollection("articles", ({ data }) => {
		return data.lang === extractRouteLangCode(import.meta.url);
	});
	return articles.map((article) => ({
		params: { slug: article.slug },
		props: { article },
	}));
}
```

Logging `extractRouteLangCode(import.meta.url)` still only return 1 locale, I think I'm not doing this correctly.
I updated the reproduction branch.

**Comment by Alexandre-Fernandez** [comment] 2023-05-18 19:26
My bad, it was an oversight. 
I know how I can fix however but the problem is the API might be non consistent and I don't like that, trying to find a better solution.

**Comment by Alexandre-Fernandez** [comment] 2023-05-18 20:25
This time it should be fixed for real, here's how to do it :
https://github.com/Alexandre-Fernandez/astro-i18n#createstaticpaths

**Closed by Alexandre-Fernandez** 2023-05-18 20:25 UTC

**Comment by narduin** [comment] 2023-05-18 21:47
Thanks again!
I'm really sorry but I'm getting an error when importing `createStaticPaths`, am I not supposed to?
```js
import { astroI18n, createStaticPaths } from "astro-i18n";
// Module '"astro-i18n"' has no exported member 'createStaticPaths'.ts(2305)
```

I tried to look at your source code to avoid bothering you but I don't understand typescript really well, sorry.

**Comment by Alexandre-Fernandez** [comment] 2023-05-18 22:01
that's weird I tried it and it worked with my local version of the library, let me try it again with the actual npm package

**Comment by Alexandre-Fernandez** [comment] 2023-05-18 22:06
@narduin I just tried it in a new project and I don't have your error.
![image](https://github.com/Alexandre-Fernandez/astro-i18n/assets/79476242/9373b012-c946-4781-b7e9-7e3d6fa4ebf1)
Try deleting `node_modules` and reinstalling, make sure it's v1.7.2.
If it doesn't work try the same but also delete the `.lock` file.

**Comment by narduin** [comment] 2023-05-18 22:23
It's working, I needed to restart vscode.
Now I just have to make this work with `getCollection`!

**Comment by narduin** [comment] 2023-05-18 23:05
Well, the markdown content is still broken but I think it might be astro's fault.
When I log the article content, the correct translated version is shown. However, **the content on the actual web page,** is not.
It feels like there might be a problem with the rendered content from [the render function](https://docs.astro.build/en/guides/content-collections/#rendering-content-to-html) `const { Content } = await article.render();` 

I'll open an issue on the astro repo.

**Comment by Alexandre-Fernandez** [comment] 2023-05-19 00:06
weird, do you have a branch where I can test that on, I'm curious, maybe I can find a solution

**Comment by narduin** [comment] 2023-05-19 00:16
I've updated the [reproduction branch](https://git.nardu.in/nardu.in/website-astro/src/branch/bug/2.4.4) where I implemented [your fix here.](https://git.nardu.in/nardu.in/website-astro/src/branch/bug/2.4.4/src/pages/articles/%5Bslug%5D.astro)

**Comment by Alexandre-Fernandez** [comment] 2023-05-19 07:59
That's weird it looks like it works just fine for me.
```
astro 2.5.0
astro-i18n 1.7.2
```
![image](https://github.com/Alexandre-Fernandez/astro-i18n/assets/79476242/a0f8ee89-7a34-4d9d-b774-15f400400a86)
![image](https://github.com/Alexandre-Fernandez/astro-i18n/assets/79476242/dadd961e-8c61-4735-bbd5-2ec1f3b7753f)

**Comment by narduin** [comment] 2023-05-19 08:04
Yes the frontmatter and i18n translations are working fine but not the markdown rendered content of the articles.
You can see that from the titles in the table of content from your screenshots. The second ones should be in french.

**Comment by Alexandre-Fernandez** [comment] 2023-05-19 11:34
I made a builtin replacement https://github.com/Alexandre-Fernandez/astro-i18n#rendercontent.
